require:
  - 'rubocop-rspec'
  - 'rubocop-rails'
  - 'rubocop-rspec_rails'
AllCops:
  NewCops: enable
  Exclude: 
    - 'app/services/secrets.rb'
    - 'config/environments/production.rb'
    - 'bin/*'
    - 'db/queue_schema.rb'
    - 'Gemfile'

Style/FrozenStringLiteralComment:
    Enabled: false

Style/Documentation:
    Enabled: false
Rails/ApplicationController:
    Enabled: false

RSpec/ExampleWording:
    Enabled: false
RSpec/MultipleExpectations:
    Enabled: false

Rails/Output:
    Enabled: false

Metrics/AbcSize:
    Enabled: false
Metrics/CyclomaticComplexity:
    Enabled: false
Metrics/MethodLength:
    Enabled: false
Metrics/PerceivedComplexity:
    Enabled: false
Lint/UselessAssignment:
    Enabled: false
Lint/EmptyConditionalBody:
    Enabled: false

